# The host and port for Open TSDB database used for metrics
#opentsdb_url = "http://172.20.0.2:8086"

# The name of the database used for storing metrics
#opentsdb_db = "metrics"

#opentsdb_username  = "lrdata"
#
#opentsdb_password  = "pwlrdata"
