[package]
name = "clignitas"
version = "0.1.0"
authors = ["Lu√≠s Silva <lfssilva@ua.pt>"]
edition = "2018"

[dependencies]
clap = "~2.27.0"
base64 = "0.10"
openssl = "0.10"
protobuf = "2.4.2"
rand = "0.6.5"
reqwest = "0.9.13"
rust-crypto = "0.2.36"
sawtooth-sdk = "0.2"
geohash-16 = "0.1.0"
